[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "goal-condition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface_hub>=0.28.0",
    "pyyaml>=6.0.2",
    "jaxtyping>=0.3.9",
    "matplotlib>=3.10.8",
    "mujoco>=3.6.0",
    "numpy>=2.4.4",
    "pyright>=1.1.408",
    "rerun-sdk==0.22.0",
    "scikit-learn>=1.8.0",
    "torch==2.10",
    "torchvision==0.25",
    "tqdm>=4.67.3",
    "wandb>=0.25.1",
    "pytest>=9.0.3",
    "datasets>=5.0.0",
]

[tool.pyright]
extraPaths = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/goal_condition"]
 
